### ISSUE TITLE
dandiarchive layout should reflect API not backend (girder) organization

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#142]
ATM we have 
- Collections
  - releases
    - `<identifier>`
  - drafts
    - `<identifier>`
  - ...
- Users
   - ...

All of the `...` are to be gone.

Such layout is girder "organization" driven -- e.g. we decided to have separate collections for `releases` and `drafts`.  
Our API is `dandiset/<identifier>/(draft|release-version)`.  Default landing page for a dandiset brings to the `draft`.

Having dichotomy between navigatable web UI and API is confusing.

I think, regardless how it is organized at girder level, web UI layout/navigation should better reflect API layout, and not bother users with `Collections/` top level.  Even having "dandisets/" (instead of `dandiset` as in API) instead of `Collections` would be better.

**Comment by satra** [comment]
i think that is the intent to achieve with the dandiarchive landing page and public dashboard. currently that ui is using a girder component to simplify things, but in the future a custom ui could take you to just to browse a specific dataset without the hierarchy.

**Comment by mgrauer** [comment]
I agree @yarikoptic that this should be done, but the current UI has been a placeholder until we figured out what our actual data organization and presentation should be.

Exactly as @satra says, the UI redesign should accomplish this, and has been recorded in #93 and #94. I'm going to close this issue because I think it is captured in those other two.
