### ISSUE TITLE
ingest: implementation discussion

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#15]
@mgrauer suggested that we might want some additional ec2 instance for the data injest -- to validate data before we let it/them into the archive.

I thought about it and wondered if should bother with any such staging area atll.  And my main argument for myself was: whatever we (pynwb + DANDI) consider valid today might become "invalid" tomorrow as more validation checks get established.  E.g., we did see quite a number of new checks added (and some other fixed) in bids-validator.

So I wonder if we should just limit validation to client(s) (to start with the cmdline `dandi-cli`, later possibly some JS fronted for web UI upload), and then (eventually, not for SfN ;-) ) develop into Web UI an indicator (e.g., an exclamation in some red or yellow triangle), either any particular file (or dataset as a whole) passes validation at that particular moment in time.  We could also provide email notifications (to uploader/maintainer(s), need to add to DB schema) whenever a file/dataset goes from "valid" to "invalid" state or vise versa.

NB metadata extraction could also be done "dynamically" on already present in the archive content

If we decide to go this route for re-validation of data upon changes in NWB/DANDI validation procedure, there will probably be no need for separate ingestion staging area.
Or may be there would be other purposes for staging area beyond validation/metadata extraction?

**Comment by mgrauer** [comment]
>@mgrauer suggested that we might want some additional ec2 instance for the data injest -- to validate data before we let it/them into the archive.

I think you maybe are conflating two different things that I've said, probably I did not clarify enough the difference between them. 

I have specifically mentioned the idea of a ingest process to the dandiarchive (note that this is not necessarily the same thing as an ingest process to Girder), but I haven't described what the ingest process would be because I don't have a clear idea yet, as we don't yet have clear requirements. This is something that I see as a longer term goal.

One example of an ingest process (I'm not advocating for this one, this is just an example) could be: upload compressed files to an S3 bucket, the S3 bucket object creation events trigger lambdas which download the data, uncompress it, validate it, extract metadata and compute summary statistics, then move the uncompressed file to a different S3 path and update some database with the metadata, summary statistics, provenance, and S3 storage path. Even if Girder+S3 is the ultimate place to store the metadata and blob data, having this separate ingest process from Girder allows us to scale and evolve the ingest process independently of the archive, and to keep the errors from one system from impacting the other.

I've also mentioned the use of an EC2 instance in the same region as the dandiarchive as a development helper in the near term. In these early days we are simply trying to find valid data and figure out where to put it and what metadata to extract. As there are some downloadable NWB files available to us (e.g. Buzsaki data), I thought it would be easier to pull the data into the EC2 instance and play around with it there manually, as the EC2 instance might have better bandwidth for pulling data in than other non-AWS servers, and further, once the data is on the EC2 instance, we can very quickly push it into S3 or some other dandiarchive piece, as the EC2 instance is inside AWS in the same region as the rest of dandiarchive (as opposed to downloading heavyweight data to some server and then pushing that same data to AWS). This is kind of a ingest process, but much more of a manual ingest process that is exploratory rather than what I would see as a scalable and production ready ingest process.

**Comment by mgrauer** [comment]
I think this gets subsumed into the discussion of the unified API. Some of the ideas are still relevant, but should be revisited anew in light of current circumstances.
