### ISSUE TITLE
List and get dandiset URLs are non-idiomatic

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandiarchive#193]
The list and get endpoints should be at:
* list: `GET /api/v1/dandi`
* get: `GET /api/v1/dandi/<dandiset_id>`

_Originally posted by @brianhelba in https://github.com/dandi/dandiarchive/pull/174_

**Comment by mgrauer** [comment]
We will need to coordinate with @yarikoptic about the timing of this change, as the dandi-cli is also a potential consumer of these endpoints. Yarik, does the cli use either of these specific endpoints, the list or get on dandisets?

**Comment by dchiquit** [comment]
I just added the list dandiset endpoiont, so the CLI does not use it yet. As I understand the CLI code, it does not use the get dandiset endpoint either.
The download function seem to accept a large number of URLs to download a dandiset. It will first follow redirects, so if it receives `https://dandiarchive.org/dandiset/000001` it will follow the redirect to the `https://gui.dandiarchive.org/#/dandiset-meta/<girderId>` URL and download it from there. It will always use girder ID scraped from the URL to perform the download.
It's possible that we might add some edge case code so that the download function can accept a `GET /api/v1/dandi/<dandiset_id>`, but I don't see an urgent need for that.
The upload and register commands do not use either GET.
@yarikoptic does that sound right?
