### ISSUE TITLE
Update Early Access message

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#214]
The [current message](https://github.com/dandi/dandiarchive/blob/82dd0c9c94f53ed2b4c0919d3f6e29d134096699/web/src/components/DandiAppBar.vue#L74-L75) says that we are in limited access mode and that public release isn't until March 2020. What should we update this to say?

**Comment by yarikoptic** [comment]
That it is beta, under heavy construction

**Comment by satra** [comment]
We had said we would launch it in march. I would say we have soft-launched it. 

So we should update the message with something like this:

"DANDI is now accepting datasets. To register and upload a new dataset, follow [these instructions](https://docs.google.com/document/d/1ehxd5a6Hurz7VqQDAszEpGASRTUP6muXYwJ5wgXhzU4/edit). You will need to sign in on this site with your Github account in order to register/upload data or to use the [DANDI computational hub](https://hub.dandiarchive.org). You do not need to sign in to download data using the [DANDI python client](https://github.com/dandi/dandi-cli/blob/master/README.md)."

**Comment by brianhelba** [comment]
As part of this, external links should follow #253.

**Comment by brianhelba** [comment]
@mgrauer Let's see if we can find a prominent place on the redesigned home page to add this.

**Comment by mgrauer** [comment]
All of this info is covered in the Handbook, which is now accessible from the documentation link.
