### ISSUE TITLE
Q: is there "hardcoded" chunk size girder uses to upload files to S3?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#333]
Echoing brief discussion during the call, I wondered if client was to compute checksums for uploaded content, it could also compute ETag as what amazon object expected to gain if we have clear control over how (fixed chunk size) it is uploaded by girder (client?) into S3.

**Comment by mgrauer** [comment]
If you mean the python client, the chunk size is [`1024 * 1024 * 64`](https://github.com/girder/girder/blob/master/clients/python/girder_client/__init__.py#L139).

Also see here https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/

**Comment by satra** [comment]
> Also see here https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/

that's nice!

**Comment by yarikoptic** [comment]
Hi @mgrauer , with @satra we looked into our current `dandi upload` insides. And we arrived to the `girder_client`'s _uploadContent just sends `.post` to the girder server with the content.  So it seems that all traffic upon upload does go through girder server regardless of the asset store backend.  Was that a wrong observation and somehow girder_client makes upload to S3 directly?

**Comment by mgrauer** [comment]
You are right for the Python client (I was confused on this before). When you upload via the web client, that uses redirects to sent the bytes to S3 directly (with a handshake API call to Girder per chunk), but the Python client proxies the bytes through Girder to S3.

**Comment by yarikoptic** [comment]
so while proxying it should be able to e.g. checksum the content, correct?
couldn't it then also use it as an id instead of a random one?

**Comment by mgrauer** [comment]
I'm getting lost on what problem you are trying to solve.

**Comment by satra** [comment]
@mgrauer - the link you posted is nice, but seems like something girder would have to do because it acts as a proxy. 

the problems we want to solve are twofold:
1. [verification] is s3 storing what we are asking it to store? can we do this without having to redownload and verify checksum?
2. [content addressable store] since girder is proxying uploads, then it could compute checksums during the byte transfer handshake process, and therefore it could use a content-hashed store (like the filesystem assetstore) and not a uuid store as it currently does.

ps. given girder proxy bulk parallel uploads could cause issues - need to test.

**Comment by mgrauer** [comment]
The results of this issue are to establish that using the Girder Python client proxies S3 uploads through Girder, and that we want content addressable storage instead of uuid, and checksums.

I'm going to close this as the question has been answered.
