### ISSUE TITLE
lock dandiset during publish workflow

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#336]
When a dandiset is being published, which will be a lengthy asynchronous action, lock the dandiset so that it cannot be published again while it is being published.

This is a high level issue for tracking. It will require backend and frontend work, as well as linking up with the publish workflow.

**Comment by dchiquit** [comment]
As part of the publish action, we "lock" the dandiset by including something equivalent to `locked:{userId}` on the `Folder` model. Once publish is finished, the lock is removed.

Enforcing the lock is harder. I feel like an event listener that prevents events on locked dandisets is the best way, but I haven't found a good event to use yet.
Using model save events (`model.folder.save`, `model.item.save`) doesn't work because the user who is performing the save isn't included in the event.
Using rest events is complicated because there are so many. You can't just listen to `rest.folder.put`. You have to specify the fully qualified endpoint (i.e. `rest.folder.put/:identifier/metadata`) for every endpoint to be intercepted. This would be doable if it were possible to iterate over defined endpoints, but I haven't found a way to do it yet.

I will keep looking for a way to properly handle enforcement. I would very much like to avoid modifying the access list, as I can see that going wrong in very inconvenient ways.

**Comment by dchiquit** [comment]
I have discovered the `getCurrentUser()` function so I now have a plan.

Add two endpoints, `lock` and `unlock`. These will add or remove a `locked: {user_id}` value on the dandiset model.
Add an event listener for all model mutations we want to protect (`model.folder.save`, `model.item.save`, `model.file.upload`, etc.). These will look up the root folder containing the object if necessary, and then check if that root dandiset folder has a `locked` value set. If not, the event proceeds normally. If so, then only operations performed by the user who owns the lock are permitted.

This solution will require some kind of unique `publish` user to lock the dandiset prior to publish and unlock it after completion. Yarik's client can also lock/unlock the dandiset before and after and writes to prevent publishes from being kicked off during file uploads.

@mgrauer @brianhelba thoughts? I'm working on a draft for code review now.

**Comment by mgrauer** [comment]
Fixed by #398.
