### ISSUE TITLE
Add frontend tests to new DLP

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandiarchive#362]

**Comment by dchiquit** [comment]
In my experience end-to-end tests are best at testing behavior, not appearance. The new DLP doesn't really /do/ much, so testing opportunities are slim (at least until the metadata editor is ready).
Some things to consider testing:
- extend `registerDandiset.js` to test that the newly registered dandiset has the correct `name` and `description` rendered on the page.
- a new `dandisetLandingView.js` test:
  - setup: create a new user and a new dandiset, get redirected to the DLP
  - verify that the `DandisetDetails` contains the correct data
    - Dandiset identifier is rendered twice, once in `DandisetMain` and once in `DandisetDetails`. These can be compared to ensure they match
    - Created/updated date should be today. Hour/minute accuracy tends to make tests flaky, but parsing the date shouldn't be awful.
  - click the close details chevron
  - verify that the `DandisetDetails` is not longer visible

The metadata editor would require a lot more testing since it's highly interactive, but I believe it's getting refactored soon so it shouldn't be considered here.

**Comment by yarikoptic** [comment]
In the light of #565 etc, it would indeed be very valuable if there was test battery to verify correct operation of the web UI.

**Comment by waxlamp** [comment]
Covered by webshots.
