### ISSUE TITLE
Fix CI so that PRs from others outside of org can be checked and tested

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#464]
Forking a repo and sending PRs is a common github paradigm. It seems this is broken currently in this archive.

**Comment by yarikoptic** [comment]
Such paradigm breaks whenever CI needs access to some secrets to perform testing -- those should be available only within workflow runs within "trusted" changes, that is why then workflow is to push PRs from branches in the same repo. But may be some CIs could have some way to "entrust" some forks but not other such that it would be worthwhile configuring?

**Comment by yarikoptic** [comment]
but do we need secrets here? testing shouldn't be done against deployed main instance or smth.  @jwodder is succeeding with using docker-compose to bring up a test instance for the purpose of testing in https://github.com/dandi/dandi-cli/pull/159 so I bet smth like that could be done here, and no secrets would be needed indeed.

**Comment by satra** [comment]
there are several ways to do this. the PR runs under the main repo, so it can use any secrets that the main repo uses if necessary. the analogy would be codecov - we get coverage on every PR whether from a collab in the org or an external contributor.

netlify has a github app that can integrated., etc.,. so this is about refactoring a bit how the tests are done. but i believe it can be achieved through any CI infrastructure.

there are a few different things that are tested but doable:

1. girder extension (this would happen locally on the CI)
2. gui preview (this is pure client side app, so the build just needs to be deployed to netlify)

**Comment by yarikoptic** [comment]
> the PR runs under the main repo, so it can use any secrets that the main repo uses if necessary.

I do not think so since then some malicious user could submit a PR which would reveal secrets available in the CI session.

> codecov

It is an app which is granted permissions to do WTF it needs on the repo, different situation from secrets.

But since original description doesn't actually mention: what portions of the current CI setup fail so we could discuss/address them specifially. netlify? then yes -- I am on board with your comment! ;)

**Comment by satra** [comment]
> malicious user could submit a PR which would reveal secrets 

somebody could try to change the workflow in etelemetry to see if they can but i believe github takes care of that. but in general the PR when run through actions, circle, travis has access to those secrets as part of the workflow.

**Comment by waxlamp** [comment]
According to this [doc page](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) there's a manual action to enable a public fork to run Actions from their branch, so this may be solved already. Not sure how to try this out though, since all of us have push access to the main repo already.

**Comment by waxlamp** [comment]
The organization settings already require an admin to approve workflow runs for PRs from forked repositories, and the only secret that seems to be used in any test workflows is `CODECOV_TOKEN` in dandi-cli. I'm not sure what effect that has on PRs to dandi-cli, but I think this issue can more or less be closed. If we run into serious trouble, let's reopen.
