### ISSUE TITLE
removing oneself from ownership does not change behavior

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#478]
i removed myself from DANDI:000004 as owner.

however:
1. this still shows up under my dandisets
2. this allows me to click edit metadata

i don't know what the implications are if i try to upload data to this now - since it's really not my dataset, i don't want to.

**Comment by AlmightyYakob** [comment]
Are there any console errors when you try to remove yourself as owner?

**Comment by AlmightyYakob** [comment]
I don't see you as an owner on that dandiset currently: https://gui.dandiarchive.org/#/dandiset/000004/draft

Are you saying that you can successfully remove yourself, but that the options which should now be restricted, are still available?

**Comment by satra** [comment]
> Are you saying that you can successfully remove yourself, but that the options which should now be restricted, are still available?

yup.

**Comment by AlmightyYakob** [comment]
> > Are you saying that you can successfully remove yourself, but that the options which should now be restricted, are still available?
> 
> yup.

In that case, you shouldn't be able to actually modify any data (all requests should fail), but it's still a visual bug that we should address.

**Comment by mgrauer** [comment]
I don't expect there would be console errors, as we had intended removing yourself as the dandiset owner to be a legal operation.

There are a few things going on here:

- @satra  is a superuser on Girder, so he has permission to do whatever, perhaps including edit metadata (though he might just be able to go to edit screen and not save). superuser permissions always mask other permission issues and can make debugging tricky.
- satra created the dandiset originally, so that is why this dandiset is returned in the [my dandisets list](https://github.com/dandi/dandiarchive/blob/d30abc143a776e22de8ff1814c3da4e98b32f918/girder-dandi-archive/girder_dandi_archive/rest.py#L169)
- we haven't clearly laid out the dandiset permission model, notions of ownership, how that relates to what we track in the contributors list, and what should be returned in my dandisets list

If you are a Dandiset owner, should you be able to remove yourself as owner? Remove other owners? Remove all owners?

These would be good topics to discuss in the hackathon. I'm going to remove the severity-critical label because I don't see it having a large impact on the site operation for most users.

**Comment by satra** [comment]
- this is not a superuser issue - i have two accounts - my github account, which i was using is a regular account.
- regarding ownership model, i thought we did say that any owner can be added/removed, which is why the manage ui behaves that way. 
- yes you can remove and add any owners, but the owner count has to be 1+, so you cannot remove the last remaining owner. if that's you, you cannot remove yourself.
- it should not matter whether i created it or not. the my dandisets list should reflect girder owners. if i'm in the list it should show up for me, if not it shouldn't. yes, it should show up if i created it, but if i have transferred it by adding another owner and removing myself, it should no longer be my dandiset.

there are longer term things like auditing and provenance tracking of the transition, but i thought the current behavior should not be expected from the gui, since the gui should literally depend on girder ownership information about a dandiset to set permissions for that user w.r.t the dandiset. i think this requires making a call to girder each time a user lands on a dandiset or hits the my dandiset link. since others could have added/removed the user.

so at this point it is really a gui behavior issue about how it maintains state and when it queries it from the server, rather than a server permission model issue.

**Comment by waxlamp** [comment]
I believe this issue has been fixed. However, in the course of testing the behavior out, I filed two new issues (both more minor than this one): #747, #748.
