### ISSUE TITLE
why is metadata in side panel lowercase?

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#502]
In the metadata for an individual NWB file shown on the right side panel when selecting a file, all of the text has been converted to lower case. I don't think this should be done because in the best case this is confusing and in the worst case this actually destroys meaningful information conveyed by the case of the text. 

* The "age" field used to be in ISO 8601 Duration format, "P118D", but now it has been converted to a non-compliant text field.

* Meaningful capitalization has been removed from the "genotype" field, which should read "Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt"

* In the "institution" field, the name of the institution should clearly use capitalization.

* The correct form for a binomial species name would be "Mus musculus"

etc.

In each of the above cases I will admit that the original correct strings are inferable by experts, but there is no guarantee that that will be true in general, so I would suggest we fix this before we come up against cases where this leads to misinformation. I am not sure where this error occurs, whether it is in the scraping of the metadata or the display of it.

![image](https://user-images.githubusercontent.com/844306/93713542-a72a8000-fb2a-11ea-9a31-462f721ce98e.png)

**Comment by mgrauer** [comment]
Can I steal or pivot this issue into requirements gathering for displaying asset level metadata? That is, rather than modifying what we currently have, we could start from the ground up by describing what it is we need.

The current GUI was a generic Girder Web Components metadata display which we used to bootstrap the archive. As we now have a slightly better idea of what we want from the archive, we could build a dandi specific asset level metadata display component.

One complication or consideration is to what degree should the display be NWB aware, as we will have other types of assets, which might require different display rules. This may point the way towards having our notion of Asset include some amount of type info (e.g. an NWB asset vs BIDS vs something generic).

**Comment by satra** [comment]
@mgrauer - when we redo this, the metadata display should indeed be crafted specific to the datatype and modality. this is longer term than simply displaying the asset metadata. 

in the short term, the asset metadata view should be based on the new asset meta model, which is presently generic enough to go across different types of data, but will be made more specific in a subsequent iteration.

**Comment by waxlamp** [comment]
Though the underlying concepts are still important, I believe the specific problem in this issue has been resolved (since we're no longer using GWC to display anything).
