### ISSUE TITLE
Web frontend: Add sort by identifier

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#567]
currently there is no way to list the dandisets by identifier. originally this would have matched created in the girder server, but not in the new API.

**Comment by yarikoptic** [comment]
;) I thought to file such a wishlist item but then decided that it might not be really worth it in the long run: upon migration we would just upload all original dandisets in the order of their dandiset identifiers.  Any new dandiset would be created after and thus order by creation date would be good enough.   But now I am thinking: that may be instead of "Created" we should indeed have two: "Identifier", and "Modified" (not sure what that "Modified" in DB is really reflective of ATM, most likely only about modified dandiset record, not really assets etc).
Moreover I am not really sure how useful sorting by "Name" is since those are pretty much arbitrary and searching would be more efficient to locate any specific one by name.
