### ISSUE TITLE
DJANGO_API: takes awhile for "download" buttons to appear

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#570]
Going to https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000008/draft/files?location=sub-mouse-AAYYT%2F leads to "Download" to appear one at a time and only after a number of seconds

NB I am ATM uploading to that dandiset, so might be effecting, but imho should not happen

**Comment by dchiquito** [comment]
```Feb 16 11:14:44 dandi-api heroku/router at=info method=GET path="/api/uploads/validations/ab6d7a2d6a673a3289e73d4e37e32b8400e578e13c6a587d6f845db349475257/" host=api.dandiarchive.org request_id=2e406b08-2323-483f-a0b1-10699e53b4ea fwd="129.170.233.10" dyno=web.1 connect=1ms service=152ms status=200 bytes=513 protocol=https
Feb 16 11:14:48 dandi-api heroku/worker.1 Process running mem=757M(147.9%)
Feb 16 11:14:48 dandi-api heroku/worker.1 Error R14 (Memory quota exceeded)
Feb 16 11:14:50 dandi-api app/web.1 10.45.208.208 - - [16/Feb/2021:19:14:49 +0000] "POST /api/dandisets/000008/versions/draft/assets/ HTTP/1.1" 200 1704 "-" "python-requests/2.23.0"
Feb 16 11:15:07 dandi-api heroku/worker.1 Process running mem=757M(147.9%)
Feb 16 11:15:07 dandi-api heroku/worker.1 Error R14 (Memory quota exceeded)```
Looks like it is affecting it. We probably need more than 512MB VMs to deal with DANDI-scale data. I'll see about bumping that up

**Comment by yarikoptic** [comment]
Boosting resources would be great. But also memory profiling and optimization I guess since I don't see where data size should matter much and we only touched the server with a few files

**Comment by yarikoptic** [comment]
Although, I guess buffer size for checksumming could be affecting and it should be reasonably large I guess

**Comment by dchiquito** [comment]
I believe the API timeouts are because of some poorly conceived API implementation.

When a version (probably `draft`) is serialized, we want to return the total size of the version, so we calculate it by fetching all (!) assets in that version and summing the size of each asset. Sadly, the only thing that is stored on the `AssetBlob` is an S3 path, so for each asset, a HEAD to S3 has to be performed to get the size of the blob.

This was fine in development with all services hosted locally, but now dandiset 000008 has several hundred assets that need to be queried individually every time version info is fetched.

I will work on saving asset/version size in the DB so that no external services need to be queried when doing read operations in the API.

**Comment by dchiquito** [comment]
@yarikoptic we are no longer attempting to DDOS S3, so it should be better now. Let us know if you run into more performance issues.

**Comment by yarikoptic** [comment]
THANK YOU! It does feel much better now indeed!
