### ISSUE TITLE
DJANGO_API: still highlights released if go to "draft" right after publishing

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#579]
probably because datetime is still matching a (just) released/published version to prevent "re-publishing"

![image](https://user-images.githubusercontent.com/39889/109169227-97543f00-774d-11eb-99ee-53501a02c84e.png)

**Comment by yarikoptic** [comment]
still the issue 
- URL keeps pointing to `draft` instead of the released version
- clicking on "DRAFT" among versions does not do anything (i.e. version is being highlighted)

So it seems that it is just web ui issue that it highlights a "published" version even though it is still really on the "draft"?

**Comment by waxlamp** [comment]
@yarikoptic, is there a dandiset where you can demo this bug currently?

**Comment by djarecka** [comment]
@yarikoptic - ping

**Comment by dchiquito** [comment]
Reproducing this issue requires performing a publish, so it's not something that is evident by just visiting a dandiset. If you refresh the page the problem should go away.

I can still reproduce this bug:
![image](https://user-images.githubusercontent.com/577946/141130685-4c5865f3-9418-4e87-ba10-3e2ae1c2e135.png)

I think the problem is that the route is not updated when navigating to the newly published version after clicking the published button. The system gets confused when you click "Draft" when the URL still reads `draft`, despite the current version shown being the one you just published.
