### ISSUE TITLE
DJANGO_API: reuploaded asset (but reused blob) has no download button

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#582]
just recreated 00003 and re-uploaded a file (after dandi-api migrated to new assets UUID handling) .  It seems that it reused the blob already in the store (I thought we are starting anew... may be we are but code is not aware and accesses some dated DB? might be related or not)

if you go to
https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000003/draft/files?location=sub-YutaMouse20%2F
there is no download button appearing or the asset.

**Comment by dchiquito** [comment]
The database was wiped, but the data in the bucket was not.
I'm not sure why the download button wouldn't be rendering. I will wipe the DB again and try to reupload that file.

**Comment by dchiquito** [comment]
I reuploaded https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000006/draft/files?location=sub-anm369962%2F because that's what I had handy, everything seems fine with the data. The download button is still missing.

After inspection it seems like the frontend was relying on the `GET .../assets/{uuid}` endpoint to also return version/dandiset information. That information is already available, it just has to be passed differently. I will fix it momentarily.
