### ISSUE TITLE
Investigate issue with meditor loading in dandisets 26 and 27

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#592]

**Comment by AlmightyYakob** [comment]
After some initial investigation, I believe this is an issue in the underlying component [VJSF](https://github.com/koumoul-dev/vuetify-jsonschema-form). I'd like to investigate some more, but I've been blocked by an unrelated bug and will need to continue tomorrow.

**Comment by waxlamp** [comment]
Update on this: after this morning's meeting, I believe the fix is the following:
- short term: manually delete the "weird empty entities" from the metadata for dandisets 26 and 27
- long term: do nothing, because dandi-cli will not produce broken metadata that would trigger this bug

@satra and @yarikoptic, if you agree with the short term fix, I can institute it immediately. Please let me know.

**Comment by satra** [comment]
since we will be uploading/wiping uploading things. at least in the first place this should be tested with some non-missing metadata. but perhaps the clearer thing is to check if this can be fixed in dandi-cli when we do the metadata conversion.  

there is a difference between missing metadata and invalid metadata and we should address this on the CLI side.

**Comment by AlmightyYakob** [comment]
> at least in the first place this should be tested with some non-missing metadata.

Could you clarify what you mean by this? Missing/invalid can mean a lot of things here. And what behavior would we be testing exactly?

**Comment by satra** [comment]
missing is when an item is missing (and this ok for meditor, which would allow creating a new item). invalid  is when one cannot do a roundtrip on the field or model. i.e. the code raises an exception. (and this should happen via the CLI)

invalid metadata (from a publishing sense) is when the required fields have not been provided. here the CLI and the Web UI needs to align. a complicating factor here is that json schema may not be able to capture all the intricacies. we should aim for parity through the schema, but watch out for places where that may fail.

**Comment by AlmightyYakob** [comment]
I guess I'm just confused on what we'd be aligning specifically. What should the meditor do if it encounters invalid metadata?

**Comment by satra** [comment]
i think there is some semantic mixup happening. so let me separate into:

- invalid dandiset metadata (the entire contents of the metadata field returned by the server, and may contain missing properties)

- invalid property (which is any property that contains values it should not be containing)

- a third of option is missing properties (key and value), which i am assuming the meditor can handle, since the underlying vue component can start with an empty dictionary.

of these three, the first will be common for the meditor, because not all required properties are filled out.

the second should never be encountered by the meditor, as this should be checked by the server on a POST to the dandiset (the api server doesn't do this check at this point). this check should happen through code in the dandi-cli, which would need to be integrated into the api code.

**Comment by yarikoptic** [comment]
+1 on fixing it in client in addition to manually fixing metadata meanwhile in girder since client no longer uploads dandiset.yaml for existing datasets. Please file an issue there with details/example (or a PR) and link it here

**Comment by AlmightyYakob** [comment]
Just talked offline with @satra, clarifying that there's **no** action needed on the client side.

**Comment by satra** [comment]
and by client he meant Web client ! i'll file an issue on the CLI side.

**Comment by waxlamp** [comment]
Since the "investigation" mentioned in this issue is complete, I will close. @satra, feel free to link the new dandi-cli issue in this thread in order to provide historicity.
