### ISSUE TITLE
download links take a long time to load

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#638]
~https://gui.dandiarchive.org/#/dandiset/000026/draft/files?location=sub-I46%2Fmicroscopy%2F~
https://gui.dandiarchive.org/#/dandiset/000026/draft/files?location=rawdata%2Fsub-I46%2Fses-SPIM%2F

in this view, it takes forever to create download links.

**Comment by yarikoptic** [comment]
I think it is just manifestation of some elderly "out of band" minting of signed download urls which is no longer needed: we know assets UUIDs and can just populate all of them right away!  It must be an easy issue to solve AFAIK, marking as such. And since it is annoying and greatly effects UX, raising severity.

**Comment by satra** [comment]
i think this is also a function of which api endpoint is being used. this place uses the files endpoint to get the listing of items (files, directories) at a given level, but doesn't return asset ids. then a second async process uses the specific path to get asset id/download link. but this download link has to be minted since it involves adding content-disposition, but the duration should be changed to allow for large file downloads. 

more importantly as ryan pointed out in a separate issue, we need to start showing content size alongside the filename. the file browser component will require quite a few updates for efficiency and user experience.

**Comment by yarikoptic** [comment]
> i think this is also a function of which api endpoint is being used. this place uses the files endpoint to get the listing of items (files, directories) at a given level, but doesn't return asset ids.

oh -- I didn't realize that `/assets/paths` returns just paths!   
Removing `good first issue` since I think situation is indeed trickier and likely require dandi-api tune up.  Could e.g. be implemented via implementing regex support (https://github.com/dandi/dandi-api/issues/230) and then getting `paths/` (thus to include directories as well, but disregard non-folders) and `/assets?path=PATH&regex=[^/]*` (urlencoded) to get only the assets which  have no `/` in their paths.

**Comment by yarikoptic** [comment]
actually I got a better idea!  Let me try to learn some dandi-api and prep a PR for review ;-)

**Comment by yarikoptic** [comment]
here it is: https://github.com/dandi/dandi-api/pull/261

**Comment by AlmightyYakob** [comment]
This will be addressed when https://github.com/dandi/dandi-api/issues/292 is addressed.

**Comment by waxlamp** [comment]
Not seeing a delay on the link in the description, @satra. Has that dandiset changed, or has this somehow been resolved?

**Comment by waxlamp** [comment]
Ah indeed I see a delay with this link: https://gui.dandiarchive.org/#/dandiset/000026/draft/files?location=rawdata%2Fsub-I46%2Fses-SPIM%2F. I'll update the description.

**Comment by satra** [comment]
closed via #773
