### ISSUE TITLE
Add contact support button

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#642]
May be that is what @satra already aiming for with helpdesk repo, but I might beat him to an issue: contact support button could then open new issue in that repo with a template and possibly information about which dandiset or just an origin page.

Cons: users will not search for already existing issues first. But I guess we could figure that out if duplicate issues appear in excess

**Comment by satra** [comment]
indeed that was the plan. and since people can log in with github, we can even have a simple user interface on the gui that uses their Github authorization to post an issue or discussion to the repo. 

the main thing is i wanted to channel issues into a central place that we can then transfer to specific repos that may address the issue. i also wanted a central place for people to request features and also for us to show what our highlevel roadmap is.

i kind of liked this part of datacite: https://datacite.org/roadmap.html

and i wanted to be able to pul those elements from a single repo.

**Comment by waxlamp** [comment]
With the addition of the "help" link in #731, I believe this is done.
