### ISSUE TITLE
Better UX for validation failures

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandiarchive#735]
Right now you need to hover over the grayed out Publish button to see what failed. This is hard to find and can be communicated better.

Maybe a little hovering superscript number indicating how many validation problems there are?

(Related: https://github.com/dandi/dandiarchive/issues/459)

**Comment by waxlamp** [comment]
@jtomeck, could you give us some design ideas for this?

**Comment by jtomeck** [comment]
I've actually been thinking about integrating a notifications menu to the page, but want sure if there was anything to be notified about. This could be the use case for it though. I can have a mockup for you in the morning.

**Comment by jtomeck** [comment]
<img width="473" alt="Screen Shot 2021-06-17 at 1 17 56 PM" src="https://user-images.githubusercontent.com/1560779/122444668-ca297980-cf6e-11eb-95a2-362152ffa312.png">

Sorry this took longer than expected. I sat with Mike and Roni to demo how and what validation failures occurred, so my mockup could be a bit better informed. The issues would show up in this dropdown next to the publish button and the "fix" button would take you to the meditor to show you specifically what isn't valid.

**An alternate option**
Now that I'm thinking about it though, we might not even need the list since everything that's wrong gets highlighted in the meditor anyway. It could just be the warning icon with the number of issues next to it (like shown in the mockup), as well as a tooltip that says "fix issues," and clicking the icon brings you to the meditor.

**Comment by satra** [comment]
making publish green would require addressing both meditor issues and asset issues. it may be worthwhile discussing this and figuring out a clean interface.

**Comment by jtomeck** [comment]
> asset issues

By asset issues do you mean issues with the actual files? Regardless, I think the alternate option I discussed above would be best. 

1. Show 2 icons next to the publish button:
    - [this one](https://materialdesignicons.com/icon/clipboard-alert) for metadata issues, although there could be a better one.
    - [this one](https://materialdesignicons.com/icon/database-alert) for file issues)
2. Each of them have a tooltip:
    - "Fix metadata issues"
    - "Fix asset issues"
3. Clicking on the icon will bring you to the correct place to make those fixes.

--

This is my assessment with limited knowledge on the "asset" part of it, so if more functionality is needed there let me know.

**Comment by waxlamp** [comment]
> **An alternate option**
> Now that I'm thinking about it though, we might not even need the list since everything that's wrong gets highlighted in the meditor anyway. It could just be the warning icon with the number of issues next to it (like shown in the mockup), as well as a tooltip that says "fix issues," and clicking the icon brings you to the meditor.

It's only the dandiset validation errors that can be fixed in the meditor; asset validation problems need to be listed out but AFAIU those cannot actually be fixed via the web app.

So, some way to say "there are metadata errors that you can fix by clicking here to go to the meditor" and also "here are the asset validation problems; fix them in your files and reupload" (or whatever the correct advice is) would be great.

Those callouts may be entirely too much to put into a notification dropdown. It may be that we need some kind of detailed panel listing out problems with assets. But that seems like a separate discussion with its own design iterations. For now, let's do something simpler that just shows whether there are dandiset validation errors and asset validation errors independently (like a pair of check engine lights), and let's think about how we might extend the asset validation error indicator to show more detail.

**Comment by jtomeck** [comment]
![Dandiset Landing PageDANDI-1](https://user-images.githubusercontent.com/1560779/123466066-e48dd380-d5bc-11eb-9e25-471c20d7961c.jpg)
Tooltip on disabled publish button

![Dandiset Landing PageDANDI](https://user-images.githubusercontent.com/1560779/123466136-fa9b9400-d5bc-11eb-84bf-fd5775c2a099.jpg)
Tooltip on metadata icon

![Dandiset Landing PageDANDI-4](https://user-images.githubusercontent.com/1560779/123466175-06875600-d5bd-11eb-8ce7-4bbf40af3cb8.jpg)
Tooltip on file fix icon

![Dandiset Landing PageDANDI-2](https://user-images.githubusercontent.com/1560779/123466216-16069f00-d5bd-11eb-9f71-e0883ca94046.jpg)
Dropdown for metadata fix

![Dandiset Landing PageDANDI-3](https://user-images.githubusercontent.com/1560779/123466400-4a7a5b00-d5bd-11eb-8b96-ee381306f87f.jpg)
Dropdown for file fixing. I have the copy link for each individual file, but if there's a bulk command they could use for all of them, that would be better UX. The info icon on the bottom would be come a global copy button for the entire list of files and the message would change appropriately.

**Comment by satra** [comment]
@jtomeck - this looks great. for the assets, perhaps allowing a txt file download would be good. those cannot be fixed in the browser and can also be too many to view. we should also say to fix these issues, use the DANDI CLI instead of the API.

**Comment by waxlamp** [comment]
> @jtomeck - this looks great. for the assets, perhaps allowing a txt file download would be good. those cannot be fixed in the browser and can also be too many to view. we should also say to fix these issues, use the DANDI CLI instead of the API.

What do you mean by "txt file download"?

**Comment by satra** [comment]
> What do you mean by "txt file download"?

download the asset validation errors description as a file.

**Comment by waxlamp** [comment]
I see. Before we decide on that, I'd like to understand better the intended workflow for when assets fail validation. Could you lay out a user story for how you envision it working?

A couple of pre-questions I have about it: if some asset fails validation, the fix in general is to reupload that asset, right? And the intention is for users to validate assets *locally* using `dandi-cli` (which in turn uses `dandischema`), is that right?

**Comment by satra** [comment]
asset validation can only be fixed via:
1. nwb reconversion with appropriate metadata
**AND/OR**
2. metadata update by the CLI in case the supported schema has moved on, or other metadata could be extracted.

1 has to be on the client system while 2 could potentially be done on the server as a background task if the owner authorizes.  for the moment let's focus on client fixes with CLI. there are a whole lot of things towards server side modification that we would like to implement but only in a subsequent stage.

the only API side process that could affect asset metadata is checksum computation on the blob. if that fails, the server needs to fix that. this should be an internal trigger for us rather than the user.

user processes:

assumption: in general any metadata the CLI uploads should be valid at that point in time. the CLI cannot upload invalid metadata. this should be checked and responded to by the API server.

1. user uploads draft, CLI ensures current validity. user waits for months, schema has moved on, assets are no longer valid. user needs to reupload (or in a future world, authorize automated metadata migration)
2. user 1 publishes dandiset, user 2 "links" asset into their own dandiset, now the dandiset may contain multiple schemaVersions of assets. the cli and the api should be able to support this use case without necessarily modifying the "linked" asset, unless it is placed at a different path prefix.

(*) valid means different things for dandiset vs asset metadata. dandiset metadata may be incomplete, while asset metadata uploaded + injected should always validate against the asset schema.

**Comment by waxlamp** [comment]
Thanks for this detail, @satra! So to grossly summarize, it sounds like the main friction point would be in lingering draft versions that persist across an asset metadata schema release?

In the short term I think that displaying the validation failures in a table in a modal might be easier and better than offering a text file export but we can probably do that as well.

**Comment by waxlamp** [comment]
Closed via #796
