### ISSUE TITLE
retrieving user API key

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#81]
currently getting the API key for a user requires logging into girder. how would a user retrieve this without logging into girder.

**Comment by mgrauer** [comment]
Who is the consumer and how would they get the api key? What are the scopes
for the api key?

Are they getting the token so they can use the Dandi CLI?

Is this a matter of displaying some “dandi apikey” in the Dandi GUI (
gui.dandiarchive.org) for a user, that contains read/write access?

**Comment by satra** [comment]
> Is this a matter of displaying some “dandi apikey” in the Dandi GUI (gui.dandiarchive.org) for a user, that contains read/write access?

yes

the scope is for the dandi cli to upload to staging

**Comment by satra** [comment]
also we should consider how the user can then enable uploads modifications by collaborators. not essential for march 1. but soon after that.

**Comment by mgrauer** [comment]
To clarify this task further. It is intended to be a place in the GUI where a user can get an API_KEY so that they can communicate with Girder via the DANDI-CLI. I would like this to be another row in the dropdown that opens up under a logged in User's Initials icon (so a new row above `logout` in the screenshot.

This would display an API_KEY that is created for the user, using the endpoint to POST api_key. The name of the api_key should be `dandicli`, the scopes should be `["read", "write"]`, and the duration should be 30 days (but I don't know if that really matters because the main use here is for the api_key and not for creating tokens).

It would be good to have a "refresh" icon on the side of the API_KEY to recreate it.

<img width="146" alt="Screen Shot 2020-03-03 at 1 18 28 PM" src="https://user-images.githubusercontent.com/595023/75807379-489ae180-5d53-11ea-866b-6a02c0dd2f2c.png">
