### ISSUE TITLE
view data: some "update" is happening twice?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#813]
I was admiring the speeds of refactored "View data" which now also shows directory sizes -- just awesome, great work @dandi/dandiarchive team!

I was a bit surprised to see at https://github.com/dandi/dandi-api-webshots/#000045 that rendering of dandiset 000045 with 6k assets takes only 0.8 second, while of [000020](https://github.com/dandi/dandi-api-webshots/#000020) with 4k takes over 2 seconds.  000020 has many more (didn't count) top level directories, so it gave me idea to look at frontend performance.

Profiling it showed:
![image](https://user-images.githubusercontent.com/39889/126876273-33ddf38c-3b47-446a-8af6-3b55363d85af.png)
so you can spot nearly two identical blocks on the right taking nearly identical time (~0.4sec) and both for the same spot: FunctionS @ vue.runtime.esm.js:6104

```javascript
  function addVnodes (parentElm, refElm, vnodes, startIdx, endIdx, insertedVnodeQueue) {
    for (; startIdx <= endIdx; ++startIdx) {
      createElm(vnodes[startIdx], insertedVnodeQueue, parentElm, refElm, false, vnodes, startIdx);
    }
  }
```
invoked within 

```javascript
function updateChildren (parentElm, oldCh, newCh, insertedVnodeQueue, removeOnly) {
...
    if (oldStartIdx > oldEndIdx) {
      refElm = isUndef(newCh[newEndIdx + 1]) ? null : newCh[newEndIdx + 1].elm;
      addVnodes(parentElm, refElm, newCh, newStartIdx, newEndIdx, insertedVnodeQueue);
    } else if (newStartIdx > newEndIdx) {
      removeVnodes(oldCh, oldStartIdx, oldEndIdx);
    }
```
so that addVnodes is outside of the loop , and that is where I don't quite grasp how two calls could have happened.

Anyways -- someone with better JS foo might like to look into it -- may be there is some "interactive update" mode is enabled, and thus it causes rerendering twice , which could be spared or something like that, to result in saving some time further and making interface even more fluid (well -- even heavier dandisets might be coming! ;))

**Comment by waxlamp** [comment]
It looks like the real fix here is to paginate the file browser view so that it doesn't try to display 6000 assets in one go. In fact, I think 2 seconds to render that many elements is pretty good--I don't believe there's a real performance issue here (other than, as I said, the lack of pagination).

The code you found is within the Vue runtime, which we really shouldn't need to wade into.

**Comment by waxlamp** [comment]
Closing in favor of #844.

**Comment by yarikoptic** [comment]
> The code you found is within the Vue runtime, which we really shouldn't need to wade into.

@mvandenburgh is getting a grip on that , so do not brush such an opportunity off entirely ;) as such I see #844 complimentary and not a replacement of this one, although may be with pagination (albeit dandi-api side would be the same work for the directories since needs to go through all) performance might get to the range of "I do not care"... yet to be seen I guess

**Comment by waxlamp** [comment]
> although may be with pagination (albeit dandi-api side would be the same work for the directories since needs to go through all) performance might get to the range of "I do not care"... yet to be seen I guess
> 

This is my strong suspicion. If I am wrong, I will of course re-open this issue. But my experience+intuition tells me that rendering 6000 items in 2 seconds is not actually a performance issue of double rendering anything, but rather a UX issue that is precisely solved in general by pagination.

As you said, since Mike is looking into it, let's see if solving #844 solves the performance as well.
