### ISSUE TITLE
Allow copy download link from item

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#82]
I posted an upstream issue for this, but it might be better fixed here. Either place is fine, as long as it gets fixed.

https://github.com/girder/girder_web_components/issues/225

**Comment by satra** [comment]
since this will be related to a url for an item, should we figure out where the link should sit?

the ideal link would be something like:

`dandiarchive.org/asset/{id}/`  this could return the metadata about the asset
`dandiarchive.org/asset/{id}/download` could redirect to the actual download location.

where should we implement this?

**Comment by yarikoptic** [comment]
related: #274 (that we had url with selected items reflected; no more) and #275 (guide user to dandi client)

**Comment by mgrauer** [comment]
I've asked @dchiquit to help with this because he got some cycles freed up.
