### ISSUE TITLE
Remove the material design "bloop" from file viewer items

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#868]
Clicking on the file viewer items doesn't do anything, yet it causes a huge material design "bloop" to occur. It's jarring, especially when nothing else happens.

We should additionally stop this from happening when one of the icons or the menu is clicked.

See [Mike's comment](https://github.com/dandi/dandiarchive/issues/868#issuecomment-912789953) below for a demo of the "bloop".

**Comment by yarikoptic** [comment]
is this related/duplicate of https://github.com/dandi/dandiarchive/issues/780 since I am not 100% certain I know what the "bloop" is? ;)

**Comment by djarecka** [comment]
I thought that "file viewer" means the new icon to view file, but now I'm not sure. And don't know how to recreate the problem

**Comment by mvandenburgh** [comment]
![Peek 2021-09-03 16-19](https://user-images.githubusercontent.com/37340715/132061471-34705182-473c-452a-be83-611c5c113911.gif)
Note the effect that happens when the file is clicked (the "bloop" :slightly_smiling_face: ).

@waxlamp are you saying the effect should be disabled for files + folders, or just files? It doesn't seem out of place for it to occur when clicking on folders, since that actually performs an action.

**Comment by yarikoptic** [comment]
IMHO just "doing nothing" is a waste of the UX space -- why not to implement "view" action for files, as suggested/discussed in https://github.com/dandi/dandiarchive/issues/780#issuecomment-885061015  which would be just providing download links but with correct mime types (I guess) for those which we know so browser would open them "natively" (e.g.  a json file within https://gui-staging.dandiarchive.org/#/dandiset/000018/draft/files?location=sub-emmet%2Fses-20180508%2Fanat%2F folder) instead of offering to download.  Or this is not possible?

**Comment by waxlamp** [comment]
Sorry for not being clear in my original text; see [Mike's comment](https://github.com/dandi/dandiarchive/issues/868#issuecomment-912789953) for what I meant.

I personally don't like the bloop on any of the file viewer items at all, mainly because the file viewer items are *not* material design buttons. I would like to hear from @jtomeck to either validate or contradict my feeling on this.

@yarik, this is a totally separate issue from the fact that currently nothing happens on click--let's continue the discussion in that issue. Even if we decided something should happen on click, I am very skeptical that the "bloop" should be there alongside it.

**Comment by jtomeck** [comment]
> I personally don't like the bloop on any of the file viewer items at all, mainly because the file viewer items are _not_ material design buttons. I would like to hear from @jtomeck to either validate or contradict my feeling on this.

I honestly have no strong opinions on the click effect. I don't think I'd think anything was out of place if I had clicked and that happened. I think in calling attention to it in the screencap you inadvertently emphasized it :P. I will say that Vuetify puts that effect on many things, not just buttons. Clickable list items, tabs, menu items. So, I don't think users will bat an eye at it.

**Comment by waxlamp** [comment]
Thanks Jared! Ok, let's not worry about the bloop--closing this issue.
